export const COUNTRIES_COORDINAT = [
  {
    basic_name: "Albania",
    country_code: "AL",
    alpha3: "ALB",
    numeric: 8,
    latitude: 41,
    longitude: 20,
  },
  {
    basic_name: "Algeria",
    country_code: "DZ",
    alpha3: "DZA",
    numeric: 12,
    latitude: 28,
    longitude: 3,
  },
  {
    basic_name: "Andorra",
    country_code: "AD",
    alpha3: "AND",
    numeric: 20,
    latitude: 42.5,
    longitude: 1.6,
  },
  {
    basic_name: "Angola",
    country_code: "AO",
    alpha3: "AGO",
    numeric: 24,
    latitude: -12.5,
    longitude: 18.5,
  },
  {
    basic_name: "Anguilla",
    country_code: "AI",
    alpha3: "AIA",
    numeric: 660,
    latitude: 18.25,
    longitude: -63.1667,
  },
  {
    basic_name: "Antigua and Barbuda",
    country_code: "AG",
    alpha3: "ATG",
    numeric: 28,
    latitude: 17.05,
    longitude: -61.8,
  },
  {
    basic_name: "Argentina",
    country_code: "AR",
    alpha3: "ARG",
    numeric: 32,
    latitude: -34,
    longitude: -64,
  },
  {
    basic_name: "Armenia",
    country_code: "AM",
    alpha3: "ARM",
    numeric: 51,
    latitude: 40,
    longitude: 45,
  },
  {
    basic_name: "Aruba",
    country_code: "AW",
    alpha3: "ABW",
    numeric: 533,
    latitude: 12.5,
    longitude: -69.9667,
  },
  {
    basic_name: "Australia",
    country_code: "AU",
    alpha3: "AUS",
    numeric: 36,
    latitude: -27,
    longitude: 133,
  },
  {
    basic_name: "Austria",
    country_code: "AT",
    alpha3: "AUT",
    numeric: 40,
    latitude: 47.3333,
    longitude: 13.3333,
  },
  {
    basic_name: "Azerbaijan",
    country_code: "AZ",
    alpha3: "AZE",
    numeric: 31,
    latitude: 40.5,
    longitude: 47.5,
  },
  {
    basic_name: "Bahamas",
    country_code: "BS",
    alpha3: "BHS",
    numeric: 44,
    latitude: 24.25,
    longitude: -76,
  },
  {
    basic_name: "Bahrain",
    country_code: "BH",
    alpha3: "BHR",
    numeric: 48,
    latitude: 26,
    longitude: 50.55,
  },
  {
    basic_name: "Bangladesh",
    country_code: "BD",
    alpha3: "BGD",
    numeric: 50,
    latitude: 24,
    longitude: 90,
  },
  {
    basic_name: "Barbados",
    country_code: "BB",
    alpha3: "BRB",
    numeric: 52,
    latitude: 13.1667,
    longitude: -59.5333,
  },
  {
    basic_name: "Belarus",
    country_code: "BY",
    alpha3: "BLR",
    numeric: 112,
    latitude: 53,
    longitude: 28,
  },
  {
    basic_name: "Belgium",
    country_code: "BE",
    alpha3: "BEL",
    numeric: 56,
    latitude: 50.8333,
    longitude: 4,
  },
  {
    basic_name: "Belize",
    country_code: "BZ",
    alpha3: "BLZ",
    numeric: 84,
    latitude: 17.25,
    longitude: -88.75,
  },
  {
    basic_name: "Benin",
    country_code: "BJ",
    alpha3: "BEN",
    numeric: 204,
    latitude: 9.5,
    longitude: 2.25,
  },
  {
    basic_name: "Bermuda",
    country_code: "BM",
    alpha3: "BMU",
    numeric: 60,
    latitude: 32.3333,
    longitude: -64.75,
  },
  {
    basic_name: "Bhutan",
    country_code: "BT",
    alpha3: "BTN",
    numeric: 64,
    latitude: 27.5,
    longitude: 90.5,
  },
  {
    basic_name: "Bolivia, Plurinational State of",
    country_code: "BO",
    alpha3: "BOL",
    numeric: 68,
    latitude: -17,
    longitude: -65,
  },
  {
    basic_name: "Bosnia and Herzegovina",
    country_code: "BA",
    alpha3: "BIH",
    numeric: 70,
    latitude: 44,
    longitude: 18,
  },
  {
    basic_name: "Botswana",
    country_code: "BW",
    alpha3: "BWA",
    numeric: 72,
    latitude: -22,
    longitude: 24,
  },
  {
    basic_name: "Bouvet Island",
    country_code: "BV",
    alpha3: "BVT",
    numeric: 74,
    latitude: -54.4333,
    longitude: 3.4,
  },
  {
    basic_name: "Brazil",
    country_code: "BR",
    alpha3: "BRA",
    numeric: 76,
    latitude: -10,
    longitude: -55,
  },
  {
    basic_name: "British Indian Ocean Territory",
    country_code: "IO",
    alpha3: "IOT",
    numeric: 86,
    latitude: -6,
    longitude: 71.5,
  },
  {
    basic_name: "Brunei Darussalam",
    country_code: "BN",
    alpha3: "BRN",
    numeric: 96,
    latitude: 4.5,
    longitude: 114.6667,
  },
  {
    basic_name: "Bulgaria",
    country_code: "BG",
    alpha3: "BGR",
    numeric: 100,
    latitude: 43,
    longitude: 25,
  },
  {
    basic_name: "Burkina Faso",
    country_code: "BF",
    alpha3: "BFA",
    numeric: 854,
    latitude: 13,
    longitude: -2,
  },
  {
    basic_name: "Burundi",
    country_code: "BI",
    alpha3: "BDI",
    numeric: 108,
    latitude: -3.5,
    longitude: 30,
  },
  {
    basic_name: "Cambodia",
    country_code: "KH",
    alpha3: "KHM",
    numeric: 116,
    latitude: 13,
    longitude: 105,
  },
  {
    basic_name: "Cameroon",
    country_code: "CM",
    alpha3: "CMR",
    numeric: 120,
    latitude: 6,
    longitude: 12,
  },
  {
    basic_name: "Canada",
    country_code: "CA",
    alpha3: "CAN",
    numeric: 124,
    latitude: 60,
    longitude: -95,
  },
  {
    basic_name: "Cape Verde",
    country_code: "CV",
    alpha3: "CPV",
    numeric: 132,
    latitude: 16,
    longitude: -24,
  },
  {
    basic_name: "Cayman Islands",
    country_code: "KY",
    alpha3: "CYM",
    numeric: 136,
    latitude: 19.5,
    longitude: -80.5,
  },
  {
    basic_name: "Central African Republic",
    country_code: "CF",
    alpha3: "CAF",
    numeric: 140,
    latitude: 7,
    longitude: 21,
  },
  {
    basic_name: "Chad",
    country_code: "TD",
    alpha3: "TCD",
    numeric: 148,
    latitude: 15,
    longitude: 19,
  },
  {
    basic_name: "Chile",
    country_code: "CL",
    alpha3: "CHL",
    numeric: 152,
    latitude: -30,
    longitude: -71,
  },
  {
    basic_name: "China",
    country_code: "CN",
    alpha3: "CHN",
    numeric: 156,
    latitude: 35,
    longitude: 105,
  },
  {
    basic_name: "Christmas Island",
    country_code: "CX",
    alpha3: "CXR",
    numeric: 162,
    latitude: -10.5,
    longitude: 105.6667,
  },
  {
    basic_name: "Cocos (Keeling) Islands",
    country_code: "CC",
    alpha3: "CCK",
    numeric: 166,
    latitude: -12.5,
    longitude: 96.8333,
  },
  {
    basic_name: "Colombia",
    country_code: "CO",
    alpha3: "COL",
    numeric: 170,
    latitude: 4,
    longitude: -72,
  },
  {
    basic_name: "Comoros",
    country_code: "KM",
    alpha3: "COM",
    numeric: 174,
    latitude: -12.1667,
    longitude: 44.25,
  },
  {
    basic_name: "Congo",
    country_code: "CG",
    alpha3: "COG",
    numeric: 178,
    latitude: -1,
    longitude: 15,
  },
  {
    basic_name: "Congo, the Democratic Republic of the",
    country_code: "CD",
    alpha3: "COD",
    numeric: 180,
    latitude: 0,
    longitude: 25,
  },
  {
    basic_name: "Cook Islands",
    country_code: "CK",
    alpha3: "COK",
    numeric: 184,
    latitude: -21.2333,
    longitude: -159.7667,
  },
  {
    basic_name: "Costa Rica",
    country_code: "CR",
    alpha3: "CRI",
    numeric: 188,
    latitude: 10,
    longitude: -84,
  },
  {
    basic_name: "Côte d'Ivoire",
    country_code: "CI",
    alpha3: "CIV",
    numeric: 384,
    latitude: 8,
    longitude: -5,
  },
  {
    basic_name: "Croatia",
    country_code: "HR",
    alpha3: "HRV",
    numeric: 191,
    latitude: 45.1667,
    longitude: 15.5,
  },
  {
    basic_name: "Cuba",
    country_code: "CU",
    alpha3: "CUB",
    numeric: 192,
    latitude: 21.5,
    longitude: -80,
  },
  {
    basic_name: "Cyprus",
    country_code: "CY",
    alpha3: "CYP",
    numeric: 196,
    latitude: 35,
    longitude: 33,
  },
  {
    basic_name: "Czech Republic",
    country_code: "CZ",
    alpha3: "CZE",
    numeric: 203,
    latitude: 49.75,
    longitude: 15.5,
  },
  {
    basic_name: "Denmark",
    country_code: "DK",
    alpha3: "DNK",
    numeric: 208,
    latitude: 56,
    longitude: 10,
  },
  {
    basic_name: "Djibouti",
    country_code: "DJ",
    alpha3: "DJI",
    numeric: 262,
    latitude: 11.5,
    longitude: 43,
  },
  {
    basic_name: "Dominica",
    country_code: "DM",
    alpha3: "DMA",
    numeric: 212,
    latitude: 15.4167,
    longitude: -61.3333,
  },
  {
    basic_name: "Dominican Republic",
    country_code: "DO",
    alpha3: "DOM",
    numeric: 214,
    latitude: 19,
    longitude: -70.6667,
  },
  {
    basic_name: "Ecuador",
    country_code: "EC",
    alpha3: "ECU",
    numeric: 218,
    latitude: -2,
    longitude: -77.5,
  },
  {
    basic_name: "Egypt",
    country_code: "EG",
    alpha3: "EGY",
    numeric: 818,
    latitude: 27,
    longitude: 30,
  },
  {
    basic_name: "El Salvador",
    country_code: "SV",
    alpha3: "SLV",
    numeric: 222,
    latitude: 13.8333,
    longitude: -88.9167,
  },
  {
    basic_name: "Equatorial Guinea",
    country_code: "GQ",
    alpha3: "GNQ",
    numeric: 226,
    latitude: 2,
    longitude: 10,
  },
  {
    basic_name: "Eritrea",
    country_code: "ER",
    alpha3: "ERI",
    numeric: 232,
    latitude: 15,
    longitude: 39,
  },
  {
    basic_name: "Estonia",
    country_code: "EE",
    alpha3: "EST",
    numeric: 233,
    latitude: 59,
    longitude: 26,
  },
  {
    basic_name: "Ethiopia",
    country_code: "ET",
    alpha3: "ETH",
    numeric: 231,
    latitude: 8,
    longitude: 38,
  },
  {
    basic_name: "Falkland Islands (Malvinas)",
    country_code: "FK",
    alpha3: "FLK",
    numeric: 238,
    latitude: -51.75,
    longitude: -59,
  },
  {
    basic_name: "Faroe Islands",
    country_code: "FO",
    alpha3: "FRO",
    numeric: 234,
    latitude: 62,
    longitude: -7,
  },
  {
    basic_name: "Fiji",
    country_code: "FJ",
    alpha3: "FJI",
    numeric: 242,
    latitude: -18,
    longitude: 175,
  },
  {
    basic_name: "Finland",
    country_code: "FI",
    alpha3: "FIN",
    numeric: 246,
    latitude: 64,
    longitude: 26,
  },
  {
    basic_name: "France",
    country_code: "FR",
    alpha3: "FRA",
    numeric: 250,
    latitude: 46,
    longitude: 2,
  },
  {
    basic_name: "French Guiana",
    country_code: "GF",
    alpha3: "GUF",
    numeric: 254,
    latitude: 4,
    longitude: -53,
  },
  {
    basic_name: "French Polynesia",
    country_code: "PF",
    alpha3: "PYF",
    numeric: 258,
    latitude: -15,
    longitude: -140,
  },
  {
    basic_name: "French Southern Territories",
    country_code: "TF",
    alpha3: "ATF",
    numeric: 260,
    latitude: -43,
    longitude: 67,
  },
  {
    basic_name: "Gabon",
    country_code: "GA",
    alpha3: "GAB",
    numeric: 266,
    latitude: -1,
    longitude: 11.75,
  },
  {
    basic_name: "Gambia",
    country_code: "GM",
    alpha3: "GMB",
    numeric: 270,
    latitude: 13.4667,
    longitude: -16.5667,
  },
  {
    basic_name: "Georgia",
    country_code: "GE",
    alpha3: "GEO",
    numeric: 268,
    latitude: 42,
    longitude: 43.5,
  },
  {
    basic_name: "Germany",
    country_code: "DE",
    alpha3: "DEU",
    numeric: 276,
    latitude: 51,
    longitude: 9,
  },
  {
    basic_name: "Ghana",
    country_code: "GH",
    alpha3: "GHA",
    numeric: 288,
    latitude: 8,
    longitude: -2,
  },
  {
    basic_name: "Gibraltar",
    country_code: "GI",
    alpha3: "GIB",
    numeric: 292,
    latitude: 36.1833,
    longitude: -5.3667,
  },
  {
    basic_name: "Greece",
    country_code: "GR",
    alpha3: "GRC",
    numeric: 300,
    latitude: 39,
    longitude: 22,
  },
  {
    basic_name: "Greenland",
    country_code: "GL",
    alpha3: "GRL",
    numeric: 304,
    latitude: 72,
    longitude: -40,
  },
  {
    basic_name: "Grenada",
    country_code: "GD",
    alpha3: "GRD",
    numeric: 308,
    latitude: 12.1167,
    longitude: -61.6667,
  },
  {
    basic_name: "Guadeloupe",
    country_code: "GP",
    alpha3: "GLP",
    numeric: 312,
    latitude: 16.25,
    longitude: -61.5833,
  },
  {
    basic_name: "Guam",
    country_code: "GU",
    alpha3: "GUM",
    numeric: 316,
    latitude: 13.4667,
    longitude: 144.7833,
  },
  {
    basic_name: "Guatemala",
    country_code: "GT",
    alpha3: "GTM",
    numeric: 320,
    latitude: 15.5,
    longitude: -90.25,
  },
  {
    basic_name: "Guinea",
    country_code: "GN",
    alpha3: "GIN",
    numeric: 324,
    latitude: 11,
    longitude: -10,
  },
  {
    basic_name: "Guinea-Bissau",
    country_code: "GW",
    alpha3: "GNB",
    numeric: 624,
    latitude: 12,
    longitude: -15,
  },
  {
    basic_name: "Guyana",
    country_code: "GY",
    alpha3: "GUY",
    numeric: 328,
    latitude: 5,
    longitude: -59,
  },
  {
    basic_name: "Haiti",
    country_code: "HT",
    alpha3: "HTI",
    numeric: 332,
    latitude: 19,
    longitude: -72.4167,
  },
  {
    basic_name: "Heard Island and McDonald Islands",
    country_code: "HM",
    alpha3: "HMD",
    numeric: 334,
    latitude: -53.1,
    longitude: 72.5167,
  },
  {
    basic_name: "Holy See (Vatican City State)",
    country_code: "VA",
    alpha3: "VAT",
    numeric: 336,
    latitude: 41.9,
    longitude: 12.45,
  },
  {
    basic_name: "Honduras",
    country_code: "HN",
    alpha3: "HND",
    numeric: 340,
    latitude: 15,
    longitude: -86.5,
  },
  {
    basic_name: "Hong Kong",
    country_code: "HK",
    alpha3: "HKG",
    numeric: 344,
    latitude: 22.25,
    longitude: 114.1667,
  },
  {
    basic_name: "Hungary",
    country_code: "HU",
    alpha3: "HUN",
    numeric: 348,
    latitude: 47,
    longitude: 20,
  },
  {
    basic_name: "Iceland",
    country_code: "IS",
    alpha3: "ISL",
    numeric: 352,
    latitude: 65,
    longitude: -18,
  },
  {
    basic_name: "India",
    country_code: "IN",
    alpha3: "IND",
    numeric: 356,
    latitude: 20,
    longitude: 77,
  },
  {
    basic_name: "Indonesia",
    country_code: "ID",
    alpha3: "IDN",
    numeric: 360,
    latitude: -5,
    longitude: 120,
  },
  {
    basic_name: "Iran, Islamic Republic of",
    country_code: "IR",
    alpha3: "IRN",
    numeric: 364,
    latitude: 32,
    longitude: 53,
  },
  {
    basic_name: "Iraq",
    country_code: "IQ",
    alpha3: "IRQ",
    numeric: 368,
    latitude: 33,
    longitude: 44,
  },
  {
    basic_name: "Ireland",
    country_code: "IE",
    alpha3: "IRL",
    numeric: 372,
    latitude: 53,
    longitude: -8,
  },
  {
    basic_name: "Israel",
    country_code: "IL",
    alpha3: "ISR",
    numeric: 376,
    latitude: 31.5,
    longitude: 34.75,
  },
  {
    basic_name: "Italy",
    country_code: "IT",
    alpha3: "ITA",
    numeric: 380,
    latitude: 42.8333,
    longitude: 12.8333,
  },
  {
    basic_name: "Jamaica",
    country_code: "JM",
    alpha3: "JAM",
    numeric: 388,
    latitude: 18.25,
    longitude: -77.5,
  },
  {
    basic_name: "Japan",
    country_code: "JP",
    alpha3: "JPN",
    numeric: 392,
    latitude: 36,
    longitude: 138,
  },
  {
    basic_name: "Jordan",
    country_code: "JO",
    alpha3: "JOR",
    numeric: 400,
    latitude: 31,
    longitude: 36,
  },
  {
    basic_name: "Kazakhstan",
    country_code: "KZ",
    alpha3: "KAZ",
    numeric: 398,
    latitude: 48,
    longitude: 68,
  },
  {
    basic_name: "Kenya",
    country_code: "KE",
    alpha3: "KEN",
    numeric: 404,
    latitude: 1,
    longitude: 38,
  },
  {
    basic_name: "Kiribati",
    country_code: "KI",
    alpha3: "KIR",
    numeric: 296,
    latitude: 1.4167,
    longitude: 173,
  },
  {
    basic_name: "Korea, Democratic People's Republic of",
    country_code: "KP",
    alpha3: "PRK",
    numeric: 408,
    latitude: 40,
    longitude: 127,
  },
  {
    basic_name: "Korea, Republic of",
    country_code: "KR",
    alpha3: "KOR",
    numeric: 410,
    latitude: 37,
    longitude: 127.5,
  },
  {
    basic_name: "Kuwait",
    country_code: "KW",
    alpha3: "KWT",
    numeric: 414,
    latitude: 29.3375,
    longitude: 47.6581,
  },
  {
    basic_name: "Kyrgyzstan",
    country_code: "KG",
    alpha3: "KGZ",
    numeric: 417,
    latitude: 41,
    longitude: 75,
  },
  {
    basic_name: "Lao People's Democratic Republic",
    country_code: "LA",
    alpha3: "LAO",
    numeric: 418,
    latitude: 18,
    longitude: 105,
  },
  {
    basic_name: "Latvia",
    country_code: "LV",
    alpha3: "LVA",
    numeric: 428,
    latitude: 57,
    longitude: 25,
  },
  {
    basic_name: "Lebanon",
    country_code: "LB",
    alpha3: "LBN",
    numeric: 422,
    latitude: 33.8333,
    longitude: 35.8333,
  },
  {
    basic_name: "Lesotho",
    country_code: "LS",
    alpha3: "LSO",
    numeric: 426,
    latitude: -29.5,
    longitude: 28.5,
  },
  {
    basic_name: "Liberia",
    country_code: "LR",
    alpha3: "LBR",
    numeric: 430,
    latitude: 6.5,
    longitude: -9.5,
  },
  {
    basic_name: "Libyan Arab Jamahiriya",
    country_code: "LY",
    alpha3: "LBY",
    numeric: 434,
    latitude: 25,
    longitude: 17,
  },
  {
    basic_name: "Liechtenstein",
    country_code: "LI",
    alpha3: "LIE",
    numeric: 438,
    latitude: 47.1667,
    longitude: 9.5333,
  },
  {
    basic_name: "Lithuania",
    country_code: "LT",
    alpha3: "LTU",
    numeric: 440,
    latitude: 56,
    longitude: 24,
  },
  {
    basic_name: "Luxembourg",
    country_code: "LU",
    alpha3: "LUX",
    numeric: 442,
    latitude: 49.75,
    longitude: 6.1667,
  },
  {
    basic_name: "Macao",
    country_code: "MO",
    alpha3: "MAC",
    numeric: 446,
    latitude: 22.1667,
    longitude: 113.55,
  },
  {
    basic_name: "Macedonia, the former Yugoslav Republic of",
    country_code: "MK",
    alpha3: "MKD",
    numeric: 807,
    latitude: 41.8333,
    longitude: 22,
  },
  {
    basic_name: "Madagascar",
    country_code: "MG",
    alpha3: "MDG",
    numeric: 450,
    latitude: -20,
    longitude: 47,
  },
  {
    basic_name: "Malawi",
    country_code: "MW",
    alpha3: "MWI",
    numeric: 454,
    latitude: -13.5,
    longitude: 34,
  },
  {
    basic_name: "Malaysia",
    country_code: "MY",
    alpha3: "MYS",
    numeric: 458,
    latitude: 2.5,
    longitude: 112.5,
  },
  {
    basic_name: "Maldives",
    country_code: "MV",
    alpha3: "MDV",
    numeric: 462,
    latitude: 3.25,
    longitude: 73,
  },
  {
    basic_name: "Mali",
    country_code: "ML",
    alpha3: "MLI",
    numeric: 466,
    latitude: 17,
    longitude: -4,
  },
  {
    basic_name: "Malta",
    country_code: "MT",
    alpha3: "MLT",
    numeric: 470,
    latitude: 35.8333,
    longitude: 14.5833,
  },
  {
    basic_name: "Marshall Islands",
    country_code: "MH",
    alpha3: "MHL",
    numeric: 584,
    latitude: 9,
    longitude: 168,
  },
  {
    basic_name: "Martinique",
    country_code: "MQ",
    alpha3: "MTQ",
    numeric: 474,
    latitude: 14.6667,
    longitude: -61,
  },
  {
    basic_name: "Mauritania",
    country_code: "MR",
    alpha3: "MRT",
    numeric: 478,
    latitude: 20,
    longitude: -12,
  },
  {
    basic_name: "Mauritius",
    country_code: "MU",
    alpha3: "MUS",
    numeric: 480,
    latitude: -20.2833,
    longitude: 57.55,
  },
  {
    basic_name: "Mayotte",
    country_code: "YT",
    alpha3: "MYT",
    numeric: 175,
    latitude: -12.8333,
    longitude: 45.1667,
  },
  {
    basic_name: "Mexico",
    country_code: "MX",
    alpha3: "MEX",
    numeric: 484,
    latitude: 23,
    longitude: -102,
  },
  {
    basic_name: "Micronesia, Federated States of",
    country_code: "FM",
    alpha3: "FSM",
    numeric: 583,
    latitude: 6.9167,
    longitude: 158.25,
  },
  {
    basic_name: "Moldova, Republic of",
    country_code: "MD",
    alpha3: "MDA",
    numeric: 498,
    latitude: 47,
    longitude: 29,
  },
  {
    basic_name: "Monaco",
    country_code: "MC",
    alpha3: "MCO",
    numeric: 492,
    latitude: 43.7333,
    longitude: 7.4,
  },
  {
    basic_name: "Mongolia",
    country_code: "MN",
    alpha3: "MNG",
    numeric: 496,
    latitude: 46,
    longitude: 105,
  },
  {
    basic_name: "Montenegro",
    country_code: "ME",
    alpha3: "MNE",
    numeric: 499,
    latitude: 42,
    longitude: 19,
  },
  {
    basic_name: "Montserrat",
    country_code: "MS",
    alpha3: "MSR",
    numeric: 500,
    latitude: 16.75,
    longitude: -62.2,
  },
  {
    basic_name: "Morocco",
    country_code: "MA",
    alpha3: "MAR",
    numeric: 504,
    latitude: 32,
    longitude: -5,
  },
  {
    basic_name: "Mozambique",
    country_code: "MZ",
    alpha3: "MOZ",
    numeric: 508,
    latitude: -18.25,
    longitude: 35,
  },
  {
    basic_name: "Myanmar",
    country_code: "MM",
    alpha3: "MMR",
    numeric: 104,
    latitude: 22,
    longitude: 98,
  },
  {
    basic_name: "Namibia",
    country_code: "NA",
    alpha3: "NAM",
    numeric: 516,
    latitude: -22,
    longitude: 17,
  },
  {
    basic_name: "Nauru",
    country_code: "NR",
    alpha3: "NRU",
    numeric: 520,
    latitude: -0.5333,
    longitude: 166.9167,
  },
  {
    basic_name: "Nepal",
    country_code: "NP",
    alpha3: "NPL",
    numeric: 524,
    latitude: 28,
    longitude: 84,
  },
  {
    basic_name: "Netherlands",
    country_code: "NL",
    alpha3: "NLD",
    numeric: 528,
    latitude: 52.5,
    longitude: 5.75,
  },
  {
    basic_name: "Netherlands Antilles",
    country_code: "AN",
    alpha3: "ANT",
    numeric: 530,
    latitude: 12.25,
    longitude: -68.75,
  },
  {
    basic_name: "New Caledonia",
    country_code: "NC",
    alpha3: "NCL",
    numeric: 540,
    latitude: -21.5,
    longitude: 165.5,
  },
  {
    basic_name: "New Zealand",
    country_code: "NZ",
    alpha3: "NZL",
    numeric: 554,
    latitude: -41,
    longitude: 174,
  },
  {
    basic_name: "Nicaragua",
    country_code: "NI",
    alpha3: "NIC",
    numeric: 558,
    latitude: 13,
    longitude: -85,
  },
  {
    basic_name: "Niger",
    country_code: "NE",
    alpha3: "NER",
    numeric: 562,
    latitude: 16,
    longitude: 8,
  },
  {
    basic_name: "Nigeria",
    country_code: "NG",
    alpha3: "NGA",
    numeric: 566,
    latitude: 10,
    longitude: 8,
  },
  {
    basic_name: "Niue",
    country_code: "NU",
    alpha3: "NIU",
    numeric: 570,
    latitude: -19.0333,
    longitude: -169.8667,
  },
  {
    basic_name: "Norfolk Island",
    country_code: "NF",
    alpha3: "NFK",
    numeric: 574,
    latitude: -29.0333,
    longitude: 167.95,
  },
  {
    basic_name: "Northern Mariana Islands",
    country_code: "MP",
    alpha3: "MNP",
    numeric: 580,
    latitude: 15.2,
    longitude: 145.75,
  },
  {
    basic_name: "Norway",
    country_code: "NO",
    alpha3: "NOR",
    numeric: 578,
    latitude: 62,
    longitude: 10,
  },
  {
    basic_name: "Oman",
    country_code: "OM",
    alpha3: "OMN",
    numeric: 512,
    latitude: 21,
    longitude: 57,
  },
  {
    basic_name: "Pakistan",
    country_code: "PK",
    alpha3: "PAK",
    numeric: 586,
    latitude: 30,
    longitude: 70,
  },
  {
    basic_name: "Palau",
    country_code: "PW",
    alpha3: "PLW",
    numeric: 585,
    latitude: 7.5,
    longitude: 134.5,
  },
  {
    basic_name: "Palestinian Territory, Occupied",
    country_code: "PS",
    alpha3: "PSE",
    numeric: 275,
    latitude: 32,
    longitude: 35.25,
  },
  {
    basic_name: "Panama",
    country_code: "PA",
    alpha3: "PAN",
    numeric: 591,
    latitude: 9,
    longitude: -80,
  },
  {
    basic_name: "Papua New Guinea",
    country_code: "PG",
    alpha3: "PNG",
    numeric: 598,
    latitude: -6,
    longitude: 147,
  },
  {
    basic_name: "Paraguay",
    country_code: "PY",
    alpha3: "PRY",
    numeric: 600,
    latitude: -23,
    longitude: -58,
  },
  {
    basic_name: "Peru",
    country_code: "PE",
    alpha3: "PER",
    numeric: 604,
    latitude: -10,
    longitude: -76,
  },
  {
    basic_name: "Philippines",
    country_code: "PH",
    alpha3: "PHL",
    numeric: 608,
    latitude: 13,
    longitude: 122,
  },
  {
    basic_name: "Pitcairn",
    country_code: "PN",
    alpha3: "PCN",
    numeric: 612,
    latitude: -24.7,
    longitude: -127.4,
  },
  {
    basic_name: "Poland",
    country_code: "PL",
    alpha3: "POL",
    numeric: 616,
    latitude: 52,
    longitude: 20,
  },
  {
    basic_name: "Portugal",
    country_code: "PT",
    alpha3: "PRT",
    numeric: 620,
    latitude: 39.5,
    longitude: -8,
  },
  {
    basic_name: "Puerto Rico",
    country_code: "PR",
    alpha3: "PRI",
    numeric: 630,
    latitude: 18.25,
    longitude: -66.5,
  },
  {
    basic_name: "Qatar",
    country_code: "QA",
    alpha3: "QAT",
    numeric: 634,
    latitude: 25.5,
    longitude: 51.25,
  },
  {
    basic_name: "Réunion",
    country_code: "RE",
    alpha3: "REU",
    numeric: 638,
    latitude: -21.1,
    longitude: 55.6,
  },
  {
    basic_name: "Romania",
    country_code: "RO",
    alpha3: "ROU",
    numeric: 642,
    latitude: 46,
    longitude: 25,
  },
  {
    basic_name: "Russian Federation",
    country_code: "RU",
    alpha3: "RUS",
    numeric: 643,
    latitude: 60,
    longitude: 100,
  },
  {
    basic_name: "Rwanda",
    country_code: "RW",
    alpha3: "RWA",
    numeric: 646,
    latitude: -2,
    longitude: 30,
  },
  {
    basic_name: "Saint Helena, Ascension and Tristan da Cunha",
    country_code: "SH",
    alpha3: "SHN",
    numeric: 654,
    latitude: -15.9333,
    longitude: -5.7,
  },
  {
    basic_name: "Saint Kitts and Nevis",
    country_code: "KN",
    alpha3: "KNA",
    numeric: 659,
    latitude: 17.3333,
    longitude: -62.75,
  },
  {
    basic_name: "Saint Lucia",
    country_code: "LC",
    alpha3: "LCA",
    numeric: 662,
    latitude: 13.8833,
    longitude: -61.1333,
  },
  {
    basic_name: "Saint Pierre and Miquelon",
    country_code: "PM",
    alpha3: "SPM",
    numeric: 666,
    latitude: 46.8333,
    longitude: -56.3333,
  },
  {
    basic_name: "Saint Vincent and the Grenadines",
    country_code: "VC",
    alpha3: "VCT",
    numeric: 670,
    latitude: 13.25,
    longitude: -61.2,
  },
  {
    basic_name: "Samoa",
    country_code: "WS",
    alpha3: "WSM",
    numeric: 882,
    latitude: -13.5833,
    longitude: -172.3333,
  },
  {
    basic_name: "San Marino",
    country_code: "SM",
    alpha3: "SMR",
    numeric: 674,
    latitude: 43.7667,
    longitude: 12.4167,
  },
  {
    basic_name: "Sao Tome and Principe",
    country_code: "ST",
    alpha3: "STP",
    numeric: 678,
    latitude: 1,
    longitude: 7,
  },
  {
    basic_name: "Saudi Arabia",
    country_code: "SA",
    alpha3: "SAU",
    numeric: 682,
    latitude: 25,
    longitude: 45,
  },
  {
    basic_name: "Senegal",
    country_code: "SN",
    alpha3: "SEN",
    numeric: 686,
    latitude: 14,
    longitude: -14,
  },
  {
    basic_name: "Serbia",
    country_code: "RS",
    alpha3: "SRB",
    numeric: 688,
    latitude: 44,
    longitude: 21,
  },
  {
    basic_name: "Seychelles",
    country_code: "SC",
    alpha3: "SYC",
    numeric: 690,
    latitude: -4.5833,
    longitude: 55.6667,
  },
  {
    basic_name: "Sierra Leone",
    country_code: "SL",
    alpha3: "SLE",
    numeric: 694,
    latitude: 8.5,
    longitude: -11.5,
  },
  {
    basic_name: "Singapore",
    country_code: "SG",
    alpha3: "SGP",
    numeric: 702,
    latitude: 1.3667,
    longitude: 103.8,
  },
  {
    basic_name: "Slovakia",
    country_code: "SK",
    alpha3: "SVK",
    numeric: 703,
    latitude: 48.6667,
    longitude: 19.5,
  },
  {
    basic_name: "Slovenia",
    country_code: "SI",
    alpha3: "SVN",
    numeric: 705,
    latitude: 46,
    longitude: 15,
  },
  {
    basic_name: "Solomon Islands",
    country_code: "SB",
    alpha3: "SLB",
    numeric: 90,
    latitude: -8,
    longitude: 159,
  },
  {
    basic_name: "Somalia",
    country_code: "SO",
    alpha3: "SOM",
    numeric: 706,
    latitude: 10,
    longitude: 49,
  },
  {
    basic_name: "South Africa",
    country_code: "ZA",
    alpha3: "ZAF",
    numeric: 710,
    latitude: -29,
    longitude: 24,
  },
  {
    basic_name: "South Georgia and the South Sandwich Islands",
    country_code: "GS",
    alpha3: "SGS",
    numeric: 239,
    latitude: -54.5,
    longitude: -37,
  },
  {
    basic_name: "Spain",
    country_code: "ES",
    alpha3: "ESP",
    numeric: 724,
    latitude: 40,
    longitude: -4,
  },
  {
    basic_name: "Sri Lanka",
    country_code: "LK",
    alpha3: "LKA",
    numeric: 144,
    latitude: 7,
    longitude: 81,
  },
  {
    basic_name: "Sudan",
    country_code: "SD",
    alpha3: "SDN",
    numeric: 736,
    latitude: 15,
    longitude: 30,
  },
  {
    basic_name: "Suriname",
    country_code: "SR",
    alpha3: "SUR",
    numeric: 740,
    latitude: 4,
    longitude: -56,
  },
  {
    basic_name: "Svalbard and Jan Mayen",
    country_code: "SJ",
    alpha3: "SJM",
    numeric: 744,
    latitude: 78,
    longitude: 20,
  },
  {
    basic_name: "Swaziland",
    country_code: "SZ",
    alpha3: "SWZ",
    numeric: 748,
    latitude: -26.5,
    longitude: 31.5,
  },
  {
    basic_name: "Sweden",
    country_code: "SE",
    alpha3: "SWE",
    numeric: 752,
    latitude: 62,
    longitude: 15,
  },
  {
    basic_name: "Switzerland",
    country_code: "CH",
    alpha3: "CHE",
    numeric: 756,
    latitude: 47,
    longitude: 8,
  },
  {
    basic_name: "Syrian Arab Republic",
    country_code: "SY",
    alpha3: "SYR",
    numeric: 760,
    latitude: 35,
    longitude: 38,
  },
  {
    basic_name: "Taiwan, Province of China",
    country_code: "TW",
    alpha3: "TWN",
    numeric: 158,
    latitude: 23.5,
    longitude: 121,
  },
  {
    basic_name: "Tajikistan",
    country_code: "TJ",
    alpha3: "TJK",
    numeric: 762,
    latitude: 39,
    longitude: 71,
  },
  {
    basic_name: "Tanzania, United Republic of",
    country_code: "TZ",
    alpha3: "TZA",
    numeric: 834,
    latitude: -6,
    longitude: 35,
  },
  {
    basic_name: "Thailand",
    country_code: "TH",
    alpha3: "THA",
    numeric: 764,
    latitude: 15,
    longitude: 100,
  },
  {
    basic_name: "Timor-Leste",
    country_code: "TL",
    alpha3: "TLS",
    numeric: 626,
    latitude: -8.55,
    longitude: 125.5167,
  },
  {
    basic_name: "Togo",
    country_code: "TG",
    alpha3: "TGO",
    numeric: 768,
    latitude: 8,
    longitude: 1.1667,
  },
  {
    basic_name: "Tokelau",
    country_code: "TK",
    alpha3: "TKL",
    numeric: 772,
    latitude: -9,
    longitude: -172,
  },
  {
    basic_name: "Tonga",
    country_code: "TO",
    alpha3: "TON",
    numeric: 776,
    latitude: -20,
    longitude: -175,
  },
  {
    basic_name: "Trinidad and Tobago",
    country_code: "TT",
    alpha3: "TTO",
    numeric: 780,
    latitude: 11,
    longitude: -61,
  },
  {
    basic_name: "Tunisia",
    country_code: "TN",
    alpha3: "TUN",
    numeric: 788,
    latitude: 34,
    longitude: 9,
  },
  {
    basic_name: "Turkey",
    country_code: "TR",
    alpha3: "TUR",
    numeric: 792,
    latitude: 39,
    longitude: 35,
  },
  {
    basic_name: "Turkmenistan",
    country_code: "TM",
    alpha3: "TKM",
    numeric: 795,
    latitude: 40,
    longitude: 60,
  },
  {
    basic_name: "Turks and Caicos Islands",
    country_code: "TC",
    alpha3: "TCA",
    numeric: 796,
    latitude: 21.75,
    longitude: -71.5833,
  },
  {
    basic_name: "Tuvalu",
    country_code: "TV",
    alpha3: "TUV",
    numeric: 798,
    latitude: -8,
    longitude: 178,
  },
  {
    basic_name: "Uganda",
    country_code: "UG",
    alpha3: "UGA",
    numeric: 800,
    latitude: 1,
    longitude: 32,
  },
  {
    basic_name: "Ukraine",
    country_code: "UA",
    alpha3: "UKR",
    numeric: 804,
    latitude: 49,
    longitude: 32,
  },
  {
    basic_name: "United Arab Emirates",
    country_code: "AE",
    alpha3: "ARE",
    numeric: 784,
    latitude: 24,
    longitude: 54,
  },
  {
    basic_name: "United Kingdom",
    country_code: "GB",
    alpha3: "GBR",
    numeric: 826,
    latitude: 54,
    longitude: -2,
  },
  {
    basic_name: "United States",
    country_code: "US",
    alpha3: "USA",
    numeric: 840,
    latitude: 38,
    longitude: -97,
  },
  {
    basic_name: "United States Minor Outlying Islands",
    country_code: "UM",
    alpha3: "UMI",
    numeric: 581,
    latitude: 19.2833,
    longitude: 166.6,
  },
  {
    basic_name: "Uruguay",
    country_code: "UY",
    alpha3: "URY",
    numeric: 858,
    latitude: -33,
    longitude: -56,
  },
  {
    basic_name: "Uzbekistan",
    country_code: "UZ",
    alpha3: "UZB",
    numeric: 860,
    latitude: 41,
    longitude: 64,
  },
  {
    basic_name: "Vanuatu",
    country_code: "VU",
    alpha3: "VUT",
    numeric: 548,
    latitude: -16,
    longitude: 167,
  },
  {
    basic_name: "Venezuela, Bolivarian Republic of",
    country_code: "VE",
    alpha3: "VEN",
    numeric: 862,
    latitude: 8,
    longitude: -66,
  },
  {
    basic_name: "Viet Nam",
    country_code: "VN",
    alpha3: "VNM",
    numeric: 704,
    latitude: 16,
    longitude: 106,
  },
  {
    basic_name: "Virgin Islands, British",
    country_code: "VG",
    alpha3: "VGB",
    numeric: 92,
    latitude: 18.5,
    longitude: -64.5,
  },
  {
    basic_name: "Virgin Islands, U.S.",
    country_code: "VI",
    alpha3: "VIR",
    numeric: 850,
    latitude: 18.3333,
    longitude: -64.8333,
  },
  {
    basic_name: "Wallis and Futuna",
    country_code: "WF",
    alpha3: "WLF",
    numeric: 876,
    latitude: -13.3,
    longitude: -176.2,
  },
  {
    basic_name: "Western Sahara",
    country_code: "EH",
    alpha3: "ESH",
    numeric: 732,
    latitude: 24.5,
    longitude: -13,
  },
  {
    basic_name: "Yemen",
    country_code: "YE",
    alpha3: "YEM",
    numeric: 887,
    latitude: 15,
    longitude: 48,
  },
  {
    basic_name: "Zambia",
    country_code: "ZM",
    alpha3: "ZMB",
    numeric: 894,
    latitude: -15,
    longitude: 30,
  },
  {
    basic_name: "Zimbabwe",
    country_code: "ZW",
    alpha3: "ZWE",
    numeric: 716,
    latitude: -20,
    longitude: 30,
  },
  {
    basic_name: "Afghanistan",
    country_code: "AF",
    alpha3: "AFG",
    numeric: 4,
    latitude: 33,
    longitude: 65,
  },
];
